name: Google Lighthouse

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        formFactor: [mobile, desktop]
        include:
          # # Using Galaxy S21 size https://blisk.io/devices/details/galaxy-s21
          - formFactor: mobile
            width: 360
            height: 800
            deviceScaleFactor: 3
            mobile: true
          - formFactor: desktop
            width: 1920
            height: 1080
            deviceScaleFactor: 1
            mobile: false
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: dawidd6/action-download-artifact@v2
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install -D @lhci/cli@latest
      - run: npx lhci collect --settings.formFactor ${{ matrix.formFactor }} --settings.screenEmulation.width ${{ matrix.width }} --settings.screenEmulation.height ${{ matrix.height }} --settings.screenEmulation.deviceScaleFactor ${{ matrix.deviceScaleFactor }} --settings.screenEmulation.mobile ${{ matrix.mobile }}
      - run: npx lhci assert
      - run: npx lhci upload --githubStatusContextSuffix /${{ matrix.formFactor }}
        if: ${{ always() }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}